services:
  - type: web
    name: rim-admin-backend
    env: node
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: rim-admin-backend
          property: port
      - key: REDIS_URL
        value: redis://red-d4bmvo0dl3ps73b0jjs0:6379
